language: php

php:
  - 7.3
  - 7.4

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - node_modules
    - vendor

env:
  global:
    - secure: "nCOrkA8kyATYUO7Pn2vF9c2KIyjAViPW1fsdHyYRVjdv0gXEYXSMUfgeQn0Ip5DBfyQU9H5Onikb99zV3WjJcjiGyaVeFAkqkEKJm1JzbBnCqCY60bLbX9twb4T8DGXw3uPQLw9wMD8JaRxqIUNUPkcLpy80adCXrAZnQ9IoD78DS2Z00Xa6Omurpx77+ImvcWFFM/qfpMEbztH+YXGY71NyEVzXv+A6s1PmC3p4wJEtuO/zr2qp/irhjgnvyn4meNeyjUnqreJYigt6qoUA2HslHJr9klr/r1oBO8Ra6JNn5F4x0cF/HOKf/xco9NzggVWkZAqkegR29ZutB2d66ZF7y4ck+dphOAYJB9LOTRCdvii7kYWbMm5PiVN80DW8MjbH/ranKPDA6ZdyU+vkrZJhj7e2k2ZV64K2mMrdMsbCztwjcwo9sginvyxVMnlODWPS8itJePePZlnxQYHU3R9IAWoiahtzYC67OoaPwPKQI7jcH4FS0tWASqHOQ6xqlOAAMrqe3CEUdUSri0z8TMn7pGXvUZYm7v0leRYvF+ysdvQSXSakW70u+2FQYVkNrYy1b1QbZW+tZ6aejTyOxOETceRhSJ2BgdS+9kv40nJv5XUQ4cqB64pGyf3J53ytzMRjEDS6QdA/LlrHH6a2jV7tJvwjgx4K7qInBQhD4GU="

before_install:
  - openssl aes-256-cbc -K $encrypted_89189802e5de_key -iv $encrypted_89189802e5de_iv -in .travis/travis_ci_snippets.enc -out .travis/travis_ci_deploy_key -d

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'create database homestead;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan config:clear
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate

script:
  - vendor/bin/phpcs --standard=PSR12 app
  - vendor/bin/phpunit

before_deploy:
  - |
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Decrypt the file containing the private key
    # (Note: this is the same as what is generated by the Travis CLI at step 2.5)
    openssl aes-256-cbc \
      -K $encrypted_89189802e5de_key \
      -iv $encrypted_89189802e5de_iv \
      -in ".travis/travis_ci_snippets.enc" \
      -out "$SSH_FILE" -d
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # Enable SSH authentication
    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
           "Host github.com" \
           "  IdentityFile $SSH_FILE" \
           "  LogLevel ERROR" >> ~/.ssh/config

deploy:
  - on:
      branch: master
      condition: -z $(git tag --points-at $TRAVIS_COMMIT)
      php: 7.4
    provider: script
    script: $TRAVIS_BUILD_DIR/.travis/travis-release.sh
